export type Theme = typeof DARK;

export const DARK = {
  bg:          "#04091E",
  bgAlt:       "#060d26",
  surface:     "rgba(255,255,255,0.03)",
  surfaceHov:  "rgba(255,255,255,0.06)",
  border:      "rgba(255,255,255,0.07)",
  borderHov:   "rgba(56,189,248,0.45)",
  text:        "#E8EAF0",
  textMuted:   "rgba(232,234,240,0.48)",
  textFaint:   "rgba(232,234,240,0.25)",
  accent:      "#38bdf8",
  accent2:     "#6366f1",
  navBg:       "rgba(4,9,30,0.92)",
  cardShadow:  "0 28px 60px rgba(0,0,0,0.5),0 0 28px rgba(56,189,248,0.08)",
  gridLine:    "rgba(56,189,248,0.04)",
  glowHero:    "rgba(56,189,248,0.12)",
  tagBg:       "rgba(56,189,248,0.08)",
  tagBorder:   "rgba(56,189,248,0.2)",
  badgeBg:     "rgba(56,189,248,0.08)",
  badgeBorder: "rgba(56,189,248,0.25)",
  statsBg:     "rgba(255,255,255,0.02)",
  statsBorder: "rgba(56,189,248,0.12)",
  ctaBg:       "linear-gradient(135deg,#0c1a4f,#0a0f35)",
  footBorder:  "rgba(56,189,248,0.1)",
  teamGrad:    "linear-gradient(160deg,rgba(14,165,233,0.12),rgba(99,102,241,0.12))",
  teamBorder:  "rgba(56,189,248,0.2)",
  scrollT:     "#0ea5e9",
  scrollTr:    "#04091E",
} as const;

export const LIGHT = {
  bg:          "#f0f4ff",
  bgAlt:       "#e6edff",
  surface:     "rgba(255,255,255,0.85)",
  surfaceHov:  "#fff",
  border:      "rgba(0,0,0,0.08)",
  borderHov:   "rgba(14,165,233,0.55)",
  text:        "#0f172a",
  textMuted:   "rgba(15,23,42,0.55)",
  textFaint:   "rgba(15,23,42,0.33)",
  accent:      "#0284c7",
  accent2:     "#4f46e5",
  navBg:       "rgba(240,244,255,0.92)",
  cardShadow:  "0 20px 50px rgba(0,0,0,0.1),0 0 20px rgba(14,165,233,0.06)",
  gridLine:    "rgba(14,165,233,0.05)",
  glowHero:    "rgba(14,165,233,0.08)",
  tagBg:       "rgba(2,132,199,0.08)",
  tagBorder:   "rgba(2,132,199,0.2)",
  badgeBg:     "rgba(2,132,199,0.07)",
  badgeBorder: "rgba(2,132,199,0.25)",
  statsBg:     "rgba(255,255,255,0.6)",
  statsBorder: "rgba(14,165,233,0.15)",
  ctaBg:       "linear-gradient(135deg,#dbeafe,#ede9fe)",
  footBorder:  "rgba(14,165,233,0.15)",
  teamGrad:    "linear-gradient(160deg,rgba(14,165,233,0.07),rgba(99,102,241,0.07))",
  teamBorder:  "rgba(14,165,233,0.18)",
  scrollT:     "#0284c7",
  scrollTr:    "#f0f4ff",
} as const;

export const TEAM_MEMBERS = [
  {
    name:    "Salman Ansari",
    role:    "Co-Founder & Developer",
    initials:"SA",
    grad:    "linear-gradient(135deg,#0ea5e9,#06b6d4)",
    bc:      "#0ea5e9",
    isCoF:   true,
    skills:  ["Web Development","SEO Expert","Content Editor","Marketing Strategist"],
    icons:   ["💻","🔍","✍️","📊"],
    bio:     "Salman is the technical brain behind Salfartech — a full-stack developer and SEO maestro who blends engineering precision with marketing intelligence. He architects digital experiences that not only look great but rank high and convert powerfully.",
  },
  {
    name:    "Farhan Ansari",
    role:    "Co-Founder & Creative Director",
    initials:"FA",
    grad:    "linear-gradient(135deg,#6366f1,#8b5cf6)",
    bc:      "#6366f1",
    isCoF:   true,
    skills:  ["Digital Artist","Creative Director","Premium Editor","Motion Graphics"],
    icons:   ["🎨","💡","🎬","✨"],
    bio:     "Farhan is the creative force of Salfartech — a visionary digital artist and motion graphics expert who transforms ideas into stunning visual narratives. His creative thinking gives every brand a distinctive, unforgettable aesthetic.",
  },
  {
    name:    "Mohd Tauheed",
    role:    "Social Media Manager & Video Editor",
    initials:"MT",
    grad:    "linear-gradient(135deg,#10b981,#0ea5e9)",
    bc:      "#10b981",
    isCoF:   false,
    skills:  ["Social Media Manager","Video Editor"],
    icons:   ["📱","🎥"],
    bio:     "Tauheed is the social pulse of Salfartech — a skilled social media manager and video editor who keeps brands consistently present and visually compelling across every platform, driving engagement and growth.",
  },
];

export const SERVICES = [
  { icon:"🌐", title:"Web Development", featured:true,
    desc:"We engineer high-performance, scalable websites and web apps that deliver exceptional user experiences and drive real business outcomes.",
    tags:["React / Next.js","Node.js","WordPress","E-Commerce","PWA","API Integration"] },
  { icon:"📈", title:"SEO", featured:false,
    desc:"Dominate search rankings with comprehensive strategies combining technical excellence and strategic link building.",
    tags:["Technical SEO","On-Page","Link Building","Local SEO"] },
  { icon:"🎯", title:"Paid Advertising", featured:false,
    desc:"Maximize ROI with precision-targeted Google and Meta campaigns, continuously optimized for lowest CPA.",
    tags:["Google Ads","Meta Ads","Retargeting","Display"] },
  { icon:"📱", title:"Social Media", featured:false,
    desc:"Build engaged communities and a powerful brand presence across all major social platforms.",
    tags:["Content Creation","Community","Influencer","Analytics"] },
  { icon:"✉️", title:"Email Marketing", featured:false,
    desc:"Nurture leads and retain customers through personalized automated email sequences.",
    tags:["Automation","Segmentation","A/B Testing","Drip Campaigns"] },
  { icon:"🎨", title:"Brand & Design", featured:false,
    desc:"Craft cohesive brand identities — logo to visual system — that make you instantly recognizable.",
    tags:["Logo Design","Visual Identity","Brand Guidelines","UI/UX"] },
  { icon:"📊", title:"Analytics", featured:false,
    desc:"Turn data into decisions with advanced dashboards, conversion tracking, and monthly reports.",
    tags:["GA4","Data Studio","Heatmaps","CRO"] },
  { icon:"🤖", title:"AI Marketing", featured:false,
    desc:"Leverage AI tools for content generation, targeting, chatbots, and predictive analytics.",
    tags:["AI Content","Chatbots","Predictive Analytics","Automation"] },
];
